"""
Purpose: Per-core service-request records — the booking-side analogue
         of SEAs for research projects.
Author: Mike Hallett (with Claude Code)
Date: 2026-05-22
Input: ``<lab_info>/cores/<core>/lab-mgmt/requests/<request_id>.md``
       (frontmatter parsed via core.frontmatter).
Output: ``RequestSummary`` per booking + state-machine helpers for
        Phase 3 lifecycle.

Distinct from ``core.requests`` (which models project-join requests
at the lab level). This module is the **service booking** record for
a core's catalog — created when a member books a slot, advances
through a state machine that mirrors SEAs:

    requested ──schedule──▶ scheduled ──start──▶ in_progress
                              │                       │
                              └──cancel──┐            └──complete──▶ completed
                                         ▼
                                     cancelled

Storage layout:

  <lab_info>/cores/<core>/lab-mgmt/requests/<request_id>.md

``request_id`` is generated by :func:`new_request_id` as
``YYYY-MM-DD-<requester>-<service>-NNN`` — sortable + human-readable
+ filename-safe. Schema in :class:`RequestSummary`; cross-reference
the cores rollout design notes §5b.

Mutations commit-audit via the existing lab_info git infrastructure
(same pattern as create_service in Phase 2c).
"""

from __future__ import annotations

import datetime as _dt
import re as _re
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any

from .frontmatter import parse_file
from .registrar import (
    LabNotFound as _LabNotFound,
    _git_commit_all,
    _git_init_if_needed,
    lab_info_root,
    read_registry as _read_registry,
)


REQUESTS_SUBDIR = "lab-mgmt/requests"

STATE_REQUESTED   = "requested"
STATE_SCHEDULED   = "scheduled"
STATE_IN_PROGRESS = "in_progress"
STATE_COMPLETED   = "completed"
STATE_CANCELLED   = "cancelled"

VALID_STATES = (
    STATE_REQUESTED, STATE_SCHEDULED, STATE_IN_PROGRESS,
    STATE_COMPLETED, STATE_CANCELLED,
)

ALLOWED_TRANSITIONS: dict[str, set[str]] = {
    STATE_REQUESTED:   {STATE_SCHEDULED, STATE_CANCELLED},
    STATE_SCHEDULED:   {STATE_IN_PROGRESS, STATE_CANCELLED},
    STATE_IN_PROGRESS: {STATE_COMPLETED, STATE_CANCELLED},
    STATE_COMPLETED:   set(),
    STATE_CANCELLED:   set(),
}

TERMINAL_STATES = {STATE_COMPLETED, STATE_CANCELLED}


class RequestError(RuntimeError):
    """Service-request mutation failed (bad transition, missing file, …)."""


@dataclass
class BookingSlot:
    """The calendar window a request occupies."""

    start: str = ""        # ISO8601 with tz, e.g. "2026-05-23T10:00-04:00"
    end: str = ""          # ISO8601 with tz
    calendar_event_id: str = ""   # opaque Google Calendar id, when wired


@dataclass
class FeeSnapshot:
    """Fees frozen at booking time. Mirrors services.quote_fee output."""

    tier: str = ""
    unit: str = "per_run"
    base: float = 0.0
    modifiers_applied: list[dict[str, Any]] = field(default_factory=list)
    total: float = 0.0


@dataclass
class RequestSummary:
    request_id: str
    service: str
    core: str
    requester: str                        # '@handle'
    requester_lab: str                    # for billing + data delivery
    state: str = STATE_REQUESTED
    booked_slot: BookingSlot = field(default_factory=BookingSlot)
    training_verified: dict[str, str] = field(default_factory=dict)
    prerequisites_attested: list[dict[str, bool]] = field(default_factory=list)
    fee_at_booking: FeeSnapshot = field(default_factory=FeeSnapshot)
    # Phase 4a: leader confirms the final charge post-run; may differ
    # from fee_at_booking (overtime, sample re-runs, …). None ≡ not yet
    # confirmed; the invoice generator falls back to fee_at_booking in
    # that case but flags the row.
    actual_charge: FeeSnapshot | None = None
    actual_charge_note: str = ""
    actual_charge_confirmed_by: str = ""
    actual_charge_confirmed_at: str = ""
    notes: str = ""
    job_id: str = ""                      # data-delivery dir name
    created: str = ""
    updated: str = ""
    path: Path | None = None


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

def requests_dir(core: str, env: dict[str, str] | None = None) -> Path:
    """``<lab_info>/cores/<core>/lab-mgmt/requests/``."""
    return lab_info_root(env) / "cores" / core / "lab-mgmt" / "requests"


def request_path(core: str, request_id: str,
                  env: dict[str, str] | None = None) -> Path:
    return requests_dir(core, env) / f"{request_id}.md"


# ---------------------------------------------------------------------------
# Id generator
# ---------------------------------------------------------------------------

_SLUG_BAD = _re.compile(r"[^a-z0-9]+")


def _slugify(s: str) -> str:
    return _SLUG_BAD.sub("_", (s or "").strip().lower()).strip("_") or "x"


def new_request_id(
    *,
    core: str,
    requester: str,
    service: str,
    today: _dt.date | None = None,
    env: dict[str, str] | None = None,
) -> str:
    """``YYYY-MM-DD-<requester>-<service>-NNN``."""
    today = today or _dt.date.today()
    base = f"{today.isoformat()}-{_slugify(requester)}-{_slugify(service)}"
    rdir = requests_dir(core, env)
    existing = set()
    if rdir.is_dir():
        existing = {p.stem for p in rdir.glob(f"{base}-*.md")}
    for n in range(1, 1000):
        candidate = f"{base}-{n:03d}"
        if candidate not in existing:
            return candidate
    raise RequestError(
        f"more than 1000 requests for {requester}/{service} on {today}; "
        "investigate before bumping the suffix width."
    )


# ---------------------------------------------------------------------------
# Render / parse
# ---------------------------------------------------------------------------

def _fee_dict(f: FeeSnapshot) -> dict:
    return {
        "tier": f.tier,
        "unit": f.unit,
        "base": f.base,
        "modifiers_applied": list(f.modifiers_applied or []),
        "total": f.total,
    }


def _to_dict(req: RequestSummary) -> dict:
    out = {
        "request_id": req.request_id,
        "service": req.service,
        "core": req.core,
        "requester": req.requester,
        "requester_lab": req.requester_lab,
        "state": req.state,
        "booked_slot": {
            "start": req.booked_slot.start,
            "end": req.booked_slot.end,
            "calendar_event_id": req.booked_slot.calendar_event_id,
        },
        "training_verified": dict(req.training_verified or {}),
        "prerequisites_attested": list(req.prerequisites_attested or []),
        "fee_at_booking": _fee_dict(req.fee_at_booking),
        "job_id": req.job_id,
        "created": req.created,
        "updated": req.updated,
    }
    if req.actual_charge is not None:
        out["actual_charge"] = _fee_dict(req.actual_charge)
        out["actual_charge_note"] = req.actual_charge_note
        out["actual_charge_confirmed_by"] = req.actual_charge_confirmed_by
        out["actual_charge_confirmed_at"] = req.actual_charge_confirmed_at
    return out


def _render_request_md(req: RequestSummary, body: str = "") -> str:
    import yaml as _y
    meta = _to_dict(req)
    yaml_text = _y.safe_dump(meta, sort_keys=False, allow_unicode=True).rstrip()
    body = body.strip() or f"# Request {req.request_id}"
    return f"---\n{yaml_text}\n---\n\n{body}\n"


def _parse_fee_or_none(raw) -> FeeSnapshot | None:
    if not raw or not isinstance(raw, dict):
        return None
    return FeeSnapshot(
        tier=str(raw.get("tier") or ""),
        unit=str(raw.get("unit") or "per_run"),
        base=float(raw.get("base") or 0.0),
        modifiers_applied=list(raw.get("modifiers_applied") or []),
        total=float(raw.get("total") or 0.0),
    )


def _parse_request(path: Path) -> RequestSummary | None:
    try:
        parsed = parse_file(path)
    except Exception:
        return None
    meta = parsed.meta or {}
    if not meta.get("request_id"):
        return None
    slot_raw = meta.get("booked_slot") or {}
    fee_raw = meta.get("fee_at_booking") or {}
    return RequestSummary(
        request_id=str(meta["request_id"]),
        service=str(meta.get("service") or ""),
        core=str(meta.get("core") or ""),
        requester=str(meta.get("requester") or ""),
        requester_lab=str(meta.get("requester_lab") or ""),
        state=str(meta.get("state") or STATE_REQUESTED),
        booked_slot=BookingSlot(
            start=str(slot_raw.get("start") or ""),
            end=str(slot_raw.get("end") or ""),
            calendar_event_id=str(slot_raw.get("calendar_event_id") or ""),
        ),
        training_verified=dict(meta.get("training_verified") or {}),
        prerequisites_attested=list(meta.get("prerequisites_attested") or []),
        fee_at_booking=FeeSnapshot(
            tier=str(fee_raw.get("tier") or ""),
            unit=str(fee_raw.get("unit") or "per_run"),
            base=float(fee_raw.get("base") or 0.0),
            modifiers_applied=list(fee_raw.get("modifiers_applied") or []),
            total=float(fee_raw.get("total") or 0.0),
        ),
        actual_charge=_parse_fee_or_none(meta.get("actual_charge")),
        actual_charge_note=str(meta.get("actual_charge_note") or ""),
        actual_charge_confirmed_by=str(meta.get("actual_charge_confirmed_by") or ""),
        actual_charge_confirmed_at=str(meta.get("actual_charge_confirmed_at") or ""),
        notes=(parsed.body or "").strip(),
        job_id=str(meta.get("job_id") or ""),
        created=str(meta.get("created") or ""),
        updated=str(meta.get("updated") or ""),
        path=path,
    )


# ---------------------------------------------------------------------------
# Reader
# ---------------------------------------------------------------------------

def iter_requests(
    core: str,
    *,
    state: str | None = None,
    requester: str | None = None,
    requester_lab: str | None = None,
    include_terminal: bool = True,
    env: dict[str, str] | None = None,
) -> list[RequestSummary]:
    """List requests for ``core``. Filters compose (state, requester,
    requester_lab). ``include_terminal=False`` hides completed +
    cancelled (useful for an active-only inbox view).
    Sort: newest first by ``created``."""
    rdir = requests_dir(core, env)
    if not rdir.is_dir():
        return []
    out: list[RequestSummary] = []
    requester_norm = (requester or "").lstrip("@").lower() or None
    for entry in sorted(rdir.iterdir()):
        if not entry.is_file() or entry.suffix != ".md":
            continue
        req = _parse_request(entry)
        if req is None:
            continue
        if state and req.state != state:
            continue
        if not include_terminal and req.state in TERMINAL_STATES:
            continue
        if requester_norm and req.requester.lstrip("@").lower() != requester_norm:
            continue
        if requester_lab and req.requester_lab != requester_lab:
            continue
        out.append(req)
    out.sort(key=lambda r: r.created, reverse=True)
    return out


def get_request(
    core: str,
    request_id: str,
    *,
    env: dict[str, str] | None = None,
) -> RequestSummary | None:
    path = request_path(core, request_id, env)
    if not path.is_file():
        return None
    return _parse_request(path)


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------

def _ensure_core_exists(core: str, env: dict[str, str] | None = None) -> None:
    reg = _read_registry(env)
    if not any(c.name == core for c in reg.cores):
        raise _LabNotFound(f"no core registered with short id: {core!r}")


def create_request(
    *,
    core: str,
    service: str,
    requester: str,
    requester_lab: str,
    booked_slot: BookingSlot | None = None,
    training_verified: dict[str, str] | None = None,
    prerequisites_attested: list[dict[str, bool]] | None = None,
    fee_at_booking: FeeSnapshot | None = None,
    notes: str = "",
    today: _dt.date | None = None,
    env: dict[str, str] | None = None,
) -> RequestSummary:
    """Create a new request file. State starts at ``scheduled`` if a
    ``booked_slot`` was provided, otherwise ``requested``.

    The booking endpoint (Phase 3b) wraps semantic checks around this
    primitive (training prereq, fee quote, member-active gate).
    """
    _ensure_core_exists(core, env)
    rid = new_request_id(
        core=core, requester=requester, service=service, today=today, env=env,
    )
    now_iso = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    slot = booked_slot or BookingSlot()
    state = STATE_SCHEDULED if (slot.start and slot.end) else STATE_REQUESTED
    req = RequestSummary(
        request_id=rid,
        service=service,
        core=core,
        requester=requester if requester.startswith("@") else f"@{requester}",
        requester_lab=requester_lab,
        state=state,
        booked_slot=slot,
        training_verified=dict(training_verified or {}),
        prerequisites_attested=list(prerequisites_attested or []),
        fee_at_booking=fee_at_booking or FeeSnapshot(),
        notes=notes,
        job_id=rid,   # job_id == request_id for the data-delivery layout
        created=now_iso,
        updated=now_iso,
    )
    rdir = requests_dir(core, env)
    rdir.mkdir(parents=True, exist_ok=True)
    target = rdir / f"{rid}.md"
    target.write_text(_render_request_md(req, body=notes), encoding="utf-8")
    req.path = target
    root = lab_info_root(env)
    _git_init_if_needed(root)
    _git_commit_all(root, f"core {core}: request {rid} created ({state})")
    # Phase 5a: auto-create the job dir + manifest so the leader can
    # upload deliverables as soon as the booking exists. Best-effort
    # — failure to create the job dir (e.g. lab_vm_root unwritable on
    # a member's laptop) does NOT block booking.
    try:
        from . import jobs as _jobs
        _jobs.init_job(core, req, env=env)
    except Exception:
        pass
    return req


def transition_request(
    *,
    core: str,
    request_id: str,
    to_state: str,
    note: str = "",
    env: dict[str, str] | None = None,
) -> RequestSummary:
    """Advance through the state machine. Refuses illegal transitions."""
    if to_state not in VALID_STATES:
        raise RequestError(f"unknown state: {to_state!r}")
    req = get_request(core, request_id, env=env)
    if req is None:
        raise RequestError(f"request not found: {core}/{request_id}")
    allowed = ALLOWED_TRANSITIONS.get(req.state, set())
    if to_state not in allowed:
        raise RequestError(
            f"illegal transition: {req.state!r} -> {to_state!r} "
            f"(allowed: {sorted(allowed) or 'terminal'})"
        )
    now_iso = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    updated = replace(req, state=to_state, updated=now_iso)
    body = req.notes
    if note:
        body = (body or "").rstrip() + (
            f"\n\n## {now_iso}: → {to_state}\n{note.strip()}\n"
        )
    target = request_path(core, request_id, env)
    target.write_text(_render_request_md(updated, body=body), encoding="utf-8")
    updated.path = target
    root = lab_info_root(env)
    _git_init_if_needed(root)
    _git_commit_all(root,
        f"core {core}: request {request_id} -> {to_state}")
    try:
        from . import jobs as _jobs
        _jobs.refresh_manifest(core, updated, env=env)
    except Exception:
        pass
    return updated


def update_booking_slot(
    *,
    core: str,
    request_id: str,
    booked_slot: BookingSlot,
    env: dict[str, str] | None = None,
) -> RequestSummary:
    """Replace a request's calendar window (reschedule). Doesn't
    change state; caller can chain transition_request."""
    req = get_request(core, request_id, env=env)
    if req is None:
        raise RequestError(f"request not found: {core}/{request_id}")
    now_iso = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    updated = replace(req, booked_slot=booked_slot, updated=now_iso)
    target = request_path(core, request_id, env)
    target.write_text(_render_request_md(updated, body=req.notes),
                       encoding="utf-8")
    updated.path = target
    root = lab_info_root(env)
    _git_init_if_needed(root)
    _git_commit_all(root,
        f"core {core}: request {request_id} slot updated "
        f"({booked_slot.start} -> {booked_slot.end})")
    return updated


def set_actual_charge(
    *,
    core: str,
    request_id: str,
    charge: FeeSnapshot,
    confirmed_by: str,
    note: str = "",
    env: dict[str, str] | None = None,
) -> RequestSummary:
    """Phase 4a: leader records the final billable amount post-run.

    Allowed in any state — bookings can pre-confirm overtime even
    before transitioning to completed. Replaces any previous
    actual_charge entirely (no partial-merge).
    """
    req = get_request(core, request_id, env=env)
    if req is None:
        raise RequestError(f"request not found: {core}/{request_id}")
    now_iso = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    updated = replace(
        req,
        actual_charge=charge,
        actual_charge_note=note,
        actual_charge_confirmed_by=confirmed_by.lstrip("@"),
        actual_charge_confirmed_at=now_iso,
        updated=now_iso,
    )
    body = req.notes or ""
    body = body.rstrip() + (
        f"\n\n## {now_iso}: actual_charge confirmed by @{updated.actual_charge_confirmed_by}\n"
        f"tier={charge.tier} total=${charge.total:.2f}"
        + (f" — {note.strip()}" if note.strip() else "")
        + "\n"
    )
    target = request_path(core, request_id, env)
    target.write_text(_render_request_md(updated, body=body), encoding="utf-8")
    updated.path = target
    root = lab_info_root(env)
    _git_init_if_needed(root)
    _git_commit_all(root,
        f"core {core}: request {request_id} actual_charge ${charge.total:.2f} "
        f"confirmed by @{updated.actual_charge_confirmed_by}")
    try:
        from . import jobs as _jobs
        _jobs.refresh_manifest(core, updated, env=env)
    except Exception:
        pass
    return updated


__all__ = [
    "REQUESTS_SUBDIR",
    "STATE_REQUESTED", "STATE_SCHEDULED", "STATE_IN_PROGRESS",
    "STATE_COMPLETED", "STATE_CANCELLED",
    "VALID_STATES", "ALLOWED_TRANSITIONS", "TERMINAL_STATES",
    "RequestError",
    "BookingSlot", "FeeSnapshot", "RequestSummary",
    "requests_dir", "request_path", "new_request_id",
    "iter_requests", "get_request",
    "create_request", "transition_request", "update_booking_slot",
    "set_actual_charge",
]
